import type { SearchCategoryMeta, SearchDocument } from './types';

export const SEARCH_CATEGORIES: readonly SearchCategoryMeta[] = [
  { id: 'pages', label: 'Pages' },
  { id: 'services', label: 'Services' },
  { id: 'industries', label: 'Industries' },
  { id: 'ai-solutions', label: 'AI Solutions' },
  { id: 'case-studies', label: 'Case Studies' },
  { id: 'pricing', label: 'Pricing' },
  { id: 'blog', label: 'Blog' },
] as const;

/** Frontend-only mock catalog for the command palette. */
export const SEARCH_MOCK_DOCUMENTS: readonly SearchDocument[] = [
  // Pages
  {
    id: 'page:home',
    category: 'pages',
    title: 'Home',
    description: 'Bitcraftly homepage — product engineering partner.',
    href: '/',
    keywords: ['home', 'landing', 'bitcraftly'],
  },
  {
    id: 'page:services',
    category: 'pages',
    title: 'Services',
    description: 'Web, apps, AI, mobile, design, and cloud services.',
    href: '/services',
    keywords: ['services', 'capabilities'],
  },
  {
    id: 'page:industries',
    category: 'pages',
    title: 'Industries',
    description: 'Industry-focused digital solutions and workflows.',
    href: '/industries',
    keywords: ['industries', 'verticals'],
  },
  {
    id: 'page:work',
    category: 'pages',
    title: 'Work',
    description: 'Selected product work and delivery outcomes.',
    href: '/work',
    keywords: ['work', 'portfolio', 'projects'],
  },
  {
    id: 'page:case-studies',
    category: 'pages',
    title: 'Case Studies',
    description: 'Outcome-focused engagement stories.',
    href: '/case-studies',
    keywords: ['case studies', 'results'],
  },
  {
    id: 'page:pricing',
    category: 'pages',
    title: 'Pricing',
    description: 'Packages, estimates, and transparent investment bands.',
    href: '/pricing',
    keywords: ['pricing', 'cost', 'packages'],
  },
  {
    id: 'page:blog',
    category: 'pages',
    title: 'Blog',
    description: 'Engineering, AI, performance, and SEO notes.',
    href: '/blog',
    keywords: ['blog', 'articles'],
  },
  {
    id: 'page:about',
    category: 'pages',
    title: 'About',
    description: 'About Bitcraftly and founder-led delivery.',
    href: '/about',
    keywords: ['about', 'company'],
  },
  {
    id: 'page:contact',
    category: 'pages',
    title: 'Contact',
    description: 'Book a discovery call or request a proposal.',
    href: '/contact',
    keywords: ['contact', 'consultation', 'call'],
  },
  {
    id: 'page:ai-solutions',
    category: 'pages',
    title: 'AI Solutions',
    description: 'AI engineering partner overview and capabilities.',
    href: '/services/ai-solutions',
    keywords: ['ai', 'solutions', 'agents'],
  },

  // Services
  {
    id: 'service:website',
    category: 'services',
    title: 'Website Development',
    description: 'Business and corporate websites that convert.',
    href: '/services/website-development',
    keywords: ['website', 'landing page', 'marketing site'],
  },
  {
    id: 'service:web-app',
    category: 'services',
    title: 'Web Application Development',
    description: 'Custom portals, dashboards, CRM, and ERP systems.',
    href: '/services/web-application-development',
    keywords: ['web app', 'dashboard', 'portal', 'saas'],
  },
  {
    id: 'service:mobile',
    category: 'services',
    title: 'Mobile App Development',
    description: 'iOS, Android, and React Native product builds.',
    href: '/services/mobile-app-development',
    keywords: ['mobile', 'ios', 'android', 'react native'],
  },
  {
    id: 'service:cloud',
    category: 'services',
    title: 'Cloud & DevOps',
    description: 'Deployment, CI/CD, monitoring, and infrastructure.',
    href: '/services/cloud-devops',
    keywords: ['cloud', 'devops', 'aws', 'ci/cd'],
  },
  {
    id: 'service:uiux',
    category: 'services',
    title: 'UI/UX Design',
    description: 'Product design, systems, and Figma-to-code delivery.',
    href: '/services/ui-ux-design',
    keywords: ['ui', 'ux', 'design system', 'figma'],
  },
  {
    id: 'service:crm',
    category: 'services',
    title: 'CRM Systems',
    description: 'Sales pipelines, follow-ups, and team accountability.',
    href: '/services#web-applications',
    keywords: ['crm', 'sales', 'pipeline'],
  },

  // Industries
  {
    id: 'industry:healthcare',
    category: 'industries',
    title: 'Healthcare',
    description: 'Booking, clinics, and care-ops platforms.',
    href: '/industries/healthcare',
    keywords: ['healthcare', 'clinic', 'hospital'],
  },
  {
    id: 'industry:education',
    category: 'industries',
    title: 'Education',
    description: 'Learning platforms and institute systems.',
    href: '/industries',
    keywords: ['education', 'lms', 'school'],
  },
  {
    id: 'industry:retail',
    category: 'industries',
    title: 'Retail',
    description: 'Commerce experiences and inventory visibility.',
    href: '/industries',
    keywords: ['retail', 'store', 'commerce'],
  },
  {
    id: 'industry:real-estate',
    category: 'industries',
    title: 'Real Estate',
    description: 'Project showcases and qualified lead capture.',
    href: '/industries/real-estate',
    keywords: ['real estate', 'property', 'listings'],
  },
  {
    id: 'industry:finance',
    category: 'industries',
    title: 'Finance',
    description: 'Secure customer journeys and ops tooling.',
    href: '/industries',
    keywords: ['finance', 'fintech', 'banking'],
  },
  {
    id: 'industry:manufacturing',
    category: 'industries',
    title: 'Manufacturing',
    description: 'Operations, inventory, and plant visibility.',
    href: '/industries',
    keywords: ['manufacturing', 'erp', 'factory'],
  },

  // AI Solutions
  {
    id: 'ai:chatbots',
    category: 'ai-solutions',
    title: 'AI Chatbots',
    description: 'Grounded conversational assistants for sales and support.',
    href: '/services/ai-chatbots',
    keywords: ['chatbot', 'assistant', 'whatsapp'],
  },
  {
    id: 'ai:automation',
    category: 'ai-solutions',
    title: 'AI Business Automation',
    description: 'Automate repetitive workflows with oversight.',
    href: '/services/ai-automation',
    keywords: ['automation', 'workflow', 'ops'],
  },
  {
    id: 'ai:agents',
    category: 'ai-solutions',
    title: 'AI Agents',
    description: 'Task-oriented agents for multi-step work.',
    href: '/services/ai-agents',
    keywords: ['agents', 'autonomous', 'llm'],
  },
  {
    id: 'ai:knowledge',
    category: 'ai-solutions',
    title: 'AI Knowledge Base',
    description: 'Semantic search with cited answers.',
    href: '/services/ai-solutions',
    keywords: ['rag', 'knowledge', 'search'],
  },
  {
    id: 'ai:documents',
    category: 'ai-solutions',
    title: 'AI Document Processing',
    description: 'Extract, classify, and route documents.',
    href: '/services/document-ai',
    keywords: ['documents', 'ocr', 'extraction'],
  },
  {
    id: 'ai:analytics',
    category: 'ai-solutions',
    title: 'AI Analytics',
    description: 'Narrative insights and anomaly detection.',
    href: '/services/ai-solutions',
    keywords: ['analytics', 'insights', 'metrics'],
  },

  // Case Studies
  {
    id: 'case:healthcare',
    category: 'case-studies',
    title: 'Healthcare Operations Platform',
    description: '+42% appointment bookings in 8 weeks.',
    href: '/work',
    keywords: ['healthcare', 'booking', 'case study'],
  },
  {
    id: 'case:ai-ops',
    category: 'case-studies',
    title: 'AI Operations Assistant',
    description: '−35% support resolution time with grounded AI.',
    href: '/work',
    keywords: ['ai', 'support', 'case study'],
  },
  {
    id: 'case:commerce',
    category: 'case-studies',
    title: 'Commerce Growth Suite',
    description: '+58% online conversion after relaunch.',
    href: '/work',
    keywords: ['ecommerce', 'conversion', 'case study'],
  },
  {
    id: 'case:crm',
    category: 'case-studies',
    title: 'Sales CRM Pipeline',
    description: '+29% pipeline velocity for B2B sales.',
    href: '/work',
    keywords: ['crm', 'sales', 'case study'],
  },
  {
    id: 'case:saas',
    category: 'case-studies',
    title: 'SaaS Analytics Platform',
    description: '+2.1× activation with multi-tenant dashboards.',
    href: '/work',
    keywords: ['saas', 'analytics', 'case study'],
  },

  // Pricing
  {
    id: 'pricing:hub',
    category: 'pricing',
    title: 'Pricing Overview',
    description: 'Transparent packages and AI project estimates.',
    href: '/pricing',
    keywords: ['pricing', 'estimate', 'packages'],
  },
  {
    id: 'pricing:starter',
    category: 'pricing',
    title: 'Starter Website',
    description: '₹15,000 starting from — focused business sites.',
    href: '/pricing',
    keywords: ['starter', 'website', '15000'],
  },
  {
    id: 'pricing:business',
    category: 'pricing',
    title: 'Business Website',
    description: '₹35,000 starting from — most popular website package.',
    href: '/pricing',
    keywords: ['business', 'website', '35000'],
  },
  {
    id: 'pricing:professional',
    category: 'pricing',
    title: 'Professional Website',
    description: '₹60,000 starting from — deeper content and polish.',
    href: '/pricing',
    keywords: ['professional', 'website', '60000'],
  },
  {
    id: 'pricing:ai-chatbot',
    category: 'pricing',
    title: 'AI Chatbot Package',
    description: 'Conversational AI scoped for support and sales.',
    href: '/pricing',
    keywords: ['ai', 'chatbot', 'pricing'],
  },
  {
    id: 'pricing:estimator',
    category: 'pricing',
    title: 'AI Project Estimator',
    description: 'Get a mock estimate for your next build.',
    href: '/pricing',
    keywords: ['estimator', 'quote', 'budget'],
  },

  // Blog
  {
    id: 'blog:hub',
    category: 'blog',
    title: 'Blog',
    description: 'All Bitcraftly articles and engineering notes.',
    href: '/blog',
    keywords: ['blog', 'insights'],
  },
  {
    id: 'blog:ai-features',
    category: 'blog',
    title: 'Shipping AI Product Features Without Chaos',
    description: 'Practical delivery patterns for AI features.',
    href: '/blog/shipping-ai-product-features-without-chaos',
    keywords: ['ai', 'product', 'delivery'],
  },
  {
    id: 'blog:nextjs',
    category: 'blog',
    title: 'Next.js App Router for Marketing Sites',
    description: 'Architecture notes for fast marketing surfaces.',
    href: '/blog/nextjs-app-router-architecture-for-marketing-sites',
    keywords: ['nextjs', 'app router', 'marketing'],
  },
  {
    id: 'blog:react',
    category: 'blog',
    title: 'React Composition Patterns That Age Well',
    description: 'Composable React patterns for long-lived products.',
    href: '/blog/react-composition-patterns-that-age-well',
    keywords: ['react', 'composition', 'patterns'],
  },
  {
    id: 'blog:vitals',
    category: 'blog',
    title: 'Core Web Vitals for Marketing Teams',
    description: 'Performance signals that protect conversion.',
    href: '/blog/core-web-vitals-for-marketing-teams',
    keywords: ['performance', 'vitals', 'seo'],
  },
  {
    id: 'blog:seo',
    category: 'blog',
    title: 'Technical SEO Checklist for Next.js Sites',
    description: 'Crawlability and structure essentials for Next.js.',
    href: '/blog/technical-seo-checklist-for-nextjs-sites',
    keywords: ['seo', 'nextjs', 'checklist'],
  },
] as const;

export function getCategoryLabel(category: SearchCategoryMeta['id']): string {
  return SEARCH_CATEGORIES.find((item) => item.id === category)?.label ?? category;
}

export function getSearchIndex(): readonly SearchDocument[] {
  return SEARCH_MOCK_DOCUMENTS;
}
