import { ROUTES } from '@/constants/navigation';
import { BITCRAFTLY_LEGACY_ORIGIN } from '../shared/contact-links';
import type { CostCalculatorCmsContent } from './cost-calculator.types';

/**
 * CMS-ready defaults — pricing rules, packages, and copy.
 * Hydrate from CMS without changing wizard UI components.
 */
export const COST_CALCULATOR_CONTENT: CostCalculatorCmsContent = {
  sectionId: 'cost-calculator',
  headingId: 'cost-calculator-heading',
  intro: {
    badge: 'Most asked question',
    heading: 'Website kitne mein banegi?',
    description:
      'Calculator se estimate — project, features, hosting. Payment sirf written quote approve ke baad.',
    pricingBadge: 'From ₹8,999',
    trustBadges: ['2-min estimate', 'From ₹8,999', 'Written quote first'],
    calculateCtaLabel: 'Calculate Cost',
    packagesCtaLabel: 'View Packages',
    packagesHref: `${BITCRAFTLY_LEGACY_ORIGIN}${ROUTES.pricing}`,
  },
  founder: {
    sectionId: 'founder-message',
    headingId: 'founder-message-heading',
    eyebrow: 'FOUNDER MESSAGE',
    heading: 'Hear from the founder',
    description:
      'Sanjay ka short voice message — English ya Hindi mein sunne ke liye language choose karein.',
    founderName: 'Sanjay Kr. Singh',
    founderRole: 'Founder · Frontend Architect',
    founderPhotoSrc: `${BITCRAFTLY_LEGACY_ORIGIN}/images/founder/sanjay-kr-singh.png`,
    founderPhotoAlt: 'Sanjay Kr. Singh — Tech Lead and Frontend Architect at Bitcraftly',
    trustBadges: ['Verified Founder', '20+ Years Experience', 'Direct Access'],
    languages: [
      {
        id: 'hi',
        label: 'हिंदी',
        audioSrc: `${BITCRAFTLY_LEGACY_ORIGIN}/audio/founder-message-hi.mp4`,
        transcript:
          'Main believe karta hoon: website tabhi premium hai jab business ko result de — zyada trust, faster load, clear WhatsApp enquiries. Isliye Bitcraftly par aap seedha founder se baat karte ho, scope likha milta hai, aur delivery par junior handoff nahi.',
        durationHint: 'Short voice note',
      },
      {
        id: 'en',
        label: 'English',
        audioSrc: `${BITCRAFTLY_LEGACY_ORIGIN}/audio/founder-message-en.mp3`,
        transcript:
          'I started Bitcraftly so you have one senior thread from first message to launch — the same discipline I use for scalable React and Next.js systems, applied to businesses that need trust, speed, and clarity.',
        durationHint: 'Short voice note',
      },
    ],
  },
  calculator: {
    eyebrow: 'Project cost calculator',
    heading: 'Kitna padega? — step-by-step estimate',
    description:
      'Customer type, project, features aur hosting choose karo — live breakdown dikhega. Final quote written scope ke baad confirm hota hai.',
    emptyBreakdownTitle: 'Steps complete karo — yahan live breakdown dikhega',
    emptyBreakdownHint: 'Example: Website ₹15,000 + Admin ₹10,000 + Hosting ₹3,000',
    liveBreakdownLabel: 'Live price breakdown',
    estimatedCostLabel: 'Estimated cost',
    runningTotalLabel: 'Running total',
    annualRenewalLabel: 'Annual renewal cost',
    timelineLabel: 'Estimated timeline',
    packageLabel: 'Suggested package',
    stackLabel: 'Recommended tech stack',
    disclaimer: 'Estimate only · 50% advance · written scope before payment · GST as applicable',
    backLabel: 'Back',
    nextLabel: 'Next',
    stickyEstimateLabel: 'View estimate',
    storageKey: 'bitcraftly.pricing-calculator.v2',
  },
  actions: {
    bookConsultationHref: `${ROUTES.contact}?intent=consultation&source=project-cost-calculator`,
    bookConsultationLabel: 'Book Consultation',
    requestQuoteHref: `${ROUTES.contact}?intent=quote&source=project-cost-calculator`,
    requestQuoteLabel: 'Request Detailed Quote',
    downloadEstimateLabel: 'Download Estimate PDF',
  },
  steps: [
    {
      id: 'customer',
      label: 'Customer',
      tip: 'Personal ya Business — seedha package nahi chahiye to yahan se custom estimate banao.',
    },
    {
      id: 'project',
      label: 'Project',
      tip: 'Project type select karo — website, SaaS, mobile, ERP, etc.',
    },
    {
      id: 'features',
      label: 'Features',
      tip: 'Optional features add karo — auth, CMS, payment, AI. Skip bhi kar sakte ho.',
    },
    {
      id: 'hosting',
      label: 'Hosting',
      tip: 'Domain/hosting — already hai ya hum setup karein. Maintenance optional hai.',
    },
    {
      id: 'timeline',
      label: 'Timeline',
      tip: 'Standard, fast-launch, ya rush — delivery window choose karo.',
    },
    {
      id: 'summary',
      label: 'Summary',
      tip: 'Selections review karo — right panel pe final estimate ready hai.',
    },
  ],
  customers: [
    {
      id: 'personal',
      label: 'Personal',
      description: 'Portfolio, personal brand, or individual project',
      icon: 'star',
    },
    {
      id: 'business',
      label: 'Business',
      description: 'Company, SaaS, institute, store, or operations',
      icon: 'layout-grid',
    },
  ],
  projectTypes: [
    {
      id: 'website',
      label: 'Website',
      description: 'Business, landing, or multi-page marketing site',
      icon: 'globe',
      customerIds: ['personal', 'business'],
      basePrice: 14999,
      timelineWeeksMin: 1,
      timelineWeeksMax: 2,
      recommendedStack: ['Next.js', 'React', 'Tailwind CSS', 'SEO basics'],
      suggestedPackage: 'Professional Business Website',
    },
    {
      id: 'web-app',
      label: 'Web App',
      description: 'Authenticated product UI with workflows',
      icon: 'code',
      customerIds: ['business'],
      basePrice: 49999,
      timelineWeeksMin: 3,
      timelineWeeksMax: 8,
      recommendedStack: ['Next.js', 'TypeScript', 'API routes', 'PostgreSQL'],
      suggestedPackage: 'Premium React/Next.js Website',
    },
    {
      id: 'ai-solution',
      label: 'AI Solution',
      description: 'Chat, automation, or AI-assisted workflows',
      icon: 'sparkles',
      customerIds: ['personal', 'business'],
      basePrice: 24999,
      timelineWeeksMin: 1,
      timelineWeeksMax: 4,
      recommendedStack: ['Next.js', 'OpenAI', 'WhatsApp handoff'],
      suggestedPackage: 'AI Chatbot Integration',
    },
    {
      id: 'erp',
      label: 'ERP',
      description: 'Operations, inventory, and finance modules',
      icon: 'database',
      customerIds: ['business'],
      basePrice: 149999,
      timelineWeeksMin: 8,
      timelineWeeksMax: 16,
      recommendedStack: ['Next.js', 'NestJS', 'PostgreSQL', 'Dashboards'],
      suggestedPackage: 'Custom Enterprise Build',
    },
    {
      id: 'crm',
      label: 'CRM',
      description: 'Pipeline, leads, and customer workflows',
      icon: 'headset',
      customerIds: ['business'],
      basePrice: 89999,
      timelineWeeksMin: 4,
      timelineWeeksMax: 12,
      recommendedStack: ['Next.js', 'Node.js', 'PostgreSQL', 'Auth'],
      suggestedPackage: 'Custom CRM Platform',
    },
    {
      id: 'saas',
      label: 'SaaS',
      description: 'Multi-tenant product shell and billing-ready UI',
      icon: 'rocket',
      customerIds: ['business'],
      basePrice: 79999,
      timelineWeeksMin: 4,
      timelineWeeksMax: 12,
      recommendedStack: ['Next.js', 'TypeScript', 'Stripe', 'PostgreSQL'],
      suggestedPackage: 'Startup MVP Frontend',
    },
    {
      id: 'dashboard',
      label: 'Dashboard',
      description: 'Analytics, KPI, and admin reporting views',
      icon: 'trending-up',
      customerIds: ['business'],
      basePrice: 34999,
      timelineWeeksMin: 2,
      timelineWeeksMax: 6,
      recommendedStack: ['Next.js', 'Charts', 'API integration'],
      suggestedPackage: 'Analytics Dashboard Build',
    },
    {
      id: 'mobile-app',
      label: 'Mobile App',
      description: 'React Native / Flutter product experience',
      icon: 'smartphone',
      customerIds: ['personal', 'business'],
      basePrice: 89999,
      timelineWeeksMin: 4,
      timelineWeeksMax: 14,
      recommendedStack: ['React Native', 'TypeScript', 'REST APIs'],
      suggestedPackage: 'Mobile App Development',
    },
    {
      id: 'custom-software',
      label: 'Custom Software',
      description: 'Bespoke systems scoped after discovery',
      icon: 'workflow',
      customerIds: ['personal', 'business'],
      basePrice: 99999,
      timelineWeeksMin: 4,
      timelineWeeksMax: 20,
      recommendedStack: ['Next.js', 'Python/FastAPI', 'Cloud', 'PostgreSQL'],
      suggestedPackage: 'Custom Discovery Sprint',
    },
  ],
  features: [
    {
      id: 'authentication',
      label: 'Authentication',
      description: 'Login, roles, and secure access',
      icon: 'shield',
      price: 4999,
    },
    {
      id: 'cms',
      label: 'CMS',
      description: 'Editable pages and content',
      icon: 'layout-grid',
      price: 4999,
    },
    {
      id: 'admin',
      label: 'Admin',
      description: 'Internal management screens',
      icon: 'layout-grid',
      price: 10000,
    },
    {
      id: 'dashboard',
      label: 'Dashboard',
      description: 'Analytics and KPI views',
      icon: 'trending-up',
      price: 7999,
    },
    {
      id: 'payment',
      label: 'Payment',
      description: 'Razorpay-ready checkout flows',
      icon: 'check',
      price: 8000,
    },
    {
      id: 'api',
      label: 'API',
      description: 'Third-party or custom API work',
      icon: 'code',
      price: 7999,
    },
    {
      id: 'ai-integration',
      label: 'AI Integration',
      description: 'Chat, assistants, or automation',
      icon: 'bot',
      price: 10000,
    },
  ],
  hostingOptions: [
    {
      id: 'already-have',
      label: 'I already have Domain & Hosting',
      description: 'You manage DNS & hosting',
      icon: 'check',
      price: 0,
      annualRenewal: 0,
    },
    {
      id: 'setup-for-me',
      label: 'Setup Everything For Me',
      description: 'Domain ₹1,200 + hosting ₹3,000/yr',
      icon: 'cloud',
      price: 4200,
      annualRenewal: 4200,
    },
  ],
  maintenanceOptions: [
    {
      id: 'none',
      label: 'No maintenance plan',
      description: 'Pay only for the build',
      icon: 'close',
      monthlyPrice: 0,
    },
    {
      id: 'monthly',
      label: 'Monthly care plan',
      description: 'Updates, monitoring, small fixes',
      icon: 'shield',
      monthlyPrice: 2999,
    },
  ],
  timelines: [
    {
      id: 'standard',
      label: 'Standard',
      description: 'Balanced delivery window',
      icon: 'calendar',
      multiplier: 1,
    },
    {
      id: 'fast',
      label: 'Fast-launch',
      description: 'Priority founder-led slot',
      icon: 'rocket',
      multiplier: 1.15,
    },
    {
      id: 'rush',
      label: 'Rush',
      description: 'Compressed timeline when content is ready',
      icon: 'zap',
      multiplier: 1.3,
    },
  ],
  tax: {
    enabled: false,
    label: 'GST (optional)',
    ratePercent: 18,
  },
  discount: {
    enabled: false,
    label: 'Discount',
    amount: 0,
  },
  defaultSelections: {
    customerTypeId: null,
    projectTypeId: null,
    featureIds: [],
    hostingId: null,
    maintenanceId: 'none',
    timelineId: null,
  },
};
